<a href="https://colab.research.google.com/github/loginahamdoun/Data-Mining-customer_segemntation/blob/main/Markov3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import random
import matplotlib.pyplot as plt


In [ ]:
mc_example = {'healthy': [0.7, 0.3, 0.1],
              'prediabetic': [0.2, 0.5, 0.3],
              'diabetic': [0.1, 0.2, 0.6]}

mc = pd.DataFrame(data = mc_example, index = ['healthy', 'prediabetic', 'diabetic'])

In [ ]:
health_sim = []
health_sim.append(mc.iloc[0].index[0])
health_status = np.random.choice(mc.iloc[0].index, p = mc.iloc[0])
health_sim.append(health_status)

while len(health_sim) < 5:
  health_status = np.random.choice(mc.iloc[mc.index.get_loc(health_status)].index, p = mc.iloc[mc.index.get_loc(health_status)])
  health_sim.append(health_status)

In [ ]:
health_sim


['healthy', 'healthy', 'healthy', 'healthy', 'healthy']

# Transition probabilities for the Markov model
transition_probs = np.array([[0.7, 0.2, 0.1],  # from healthy
                             [0.3, 0.5, 0.2],  # from prediabetic
                             [0.1, 0.3, 0.6]]) # from diabetic

In [ ]:
mc


healthy  prediabetic  diabetic
healthy          0.7          0.2       0.1
prediabetic      0.3          0.5       0.2
diabetic         0.1          0.3       0.6

In [ ]:
mc.to_numpy()


array([[0.7, 0.2, 0.1],
       [0.3, 0.5, 0.2],
       [0.1, 0.3, 0.6]])

In [ ]:
def matrix_power(matrix, power):
  if power == 0:
    return np.identity(len(matrix))
  elif power == 1:
    return matrix
  else:
    return np.dot(matrix, matrix_power(matrix, power-1))


In [ ]:
matrix_power(mc.to_numpy(), 2)

array([[0.56, 0.27, 0.17],
       [0.38, 0.37, 0.25],
       [0.22, 0.35, 0.43]])

In [ ]:
np.dot(np.dot(mc.to_numpy(), mc.to_numpy()), mc.to_numpy())


array([[0.49 , 0.298, 0.212],
       [0.402, 0.336, 0.262],
       [0.302, 0.348, 0.35 ]])

In [ ]:
np.dot(mc.to_numpy(), mc.to_numpy())


array([[0.56, 0.27, 0.17],
       [0.38, 0.37, 0.25],
       [0.22, 0.35, 0.43]])

In [ ]:
matrix_power(mc.to_numpy(), 3).sum(axis=1)


array([1., 1., 1.])

In [ ]:
for i in range(1,10,1):
  print(f'n Step Transition Matrix at the nth power {i}\n', matrix_power(mc.to_numpy(), i),'\n')

n Step Transition Matrix at the nth power 1
 [[0.7 0.2 0.1]
 [0.3 0.5 0.2]
 [0.1 0.3 0.6]] 

n Step Transition Matrix at the nth power 2
 [[0.56 0.27 0.17]
 [0.38 0.37 0.25]
 [0.22 0.35 0.43]] 

n Step Transition Matrix at the nth power 3
 [[0.49  0.298 0.212]
 [0.402 0.336 0.262]
 [0.302 0.348 0.35 ]] 

n Step Transition Matrix at the nth power 4
 [[0.4536 0.3106 0.2358]
 [0.4084 0.327  0.2646]
 [0.3508 0.3394 0.3098]] 

n Step Transition Matrix at the nth power 5
 [[0.43428 0.31676 0.24896]
 [0.41044 0.32456 0.265  ]
 [0.37836 0.3328  0.28884]] 

n Step Transition Matrix at the nth power 6
 [[0.42392  0.319924 0.256156]
 [0.411176 0.323868 0.264956]
 [0.393576 0.328724 0.2777  ]] 

n Step Transition Matrix at the nth power 7
 [[0.4183368 0.3215928 0.2600704]
 [0.4114792 0.323656  0.2648648]
 [0.4018904 0.3263872 0.2717224]] 

n Step Transition Matrix at the nth power 8
 [[0.41532064 0.32248488 0.26219448]
 [0.41161872 0.32358328 0.264798  ]
 [0.40641168 0.3250884  0.26849992]] 

n St

In [ ]:
initial_dist = np.asarray([0.7, 0.2, 0.1])

mc_p2 = matrix_power(mc.to_numpy(),2)

np.dot(initial_dist,mc_p2)

array([0.49 , 0.298, 0.212])